export const API_ROUTES = {
  register: "register",
  users: "users",
  profile: "profile",
  permissions: "permissions",
  options: "options",
  departments: "departments",
  departmentMember: "departments/:id",
  departmentAddMember: "departments/add-member",
  teamMember: "team-member",
  teamMemberDetail: "team-member/:id",
  milestone: "milestone",
  milestoneDetail: "milestone/:id",
  milestoneSummary: "milestone/summary",
};
