export const API_ROUTES = {
  register: "register",
  users: "users",
  profile: "profile",
  permissions: "permissions",
  options: "options",
  departments: "departments",
  departmentMember: "departments/:id",
  departmentAddMember: "departments/add-member",
  teamMember: "team-member",
  teamMemberDetail: "team-member/:id",
  milestone: "milestone",
  milestoneDetail: "milestone/:id",
  milestoneSummary: "milestone/summary",
  project: "project",
  projectDetail: "project/:id",
  workflows: "workflows",
  workflowDetail: "workflows/:id",
  workflowOptions: "workflows/options",
  categories: "categories",
  categoryDetail: "categories/:id",
  categoryOptions: "categories/options",
  documentTypes: "documentTypes",
  documentTypeDetail: "documentTypes/:id",
  documentTypeOptions: "documentTypes/options",
};
