export const PAGE_ROUTES = {
  DASHBOARD: "/",
  PROJECTS: "/projects",
  PROJECT_DETAIL: "/projects/:id",
  MILESTONES: "/milestones",
  PAYMENTS: "/payments/management",
  ASSETS: "/payments/assets",
  LIABILITIES: "/payments/liabilities",
  DOCUMENT_TYPES: "/payments/document-types",
  REPORTS_FINANCIAL: "/reports/financial",
  REPORTS_SUMMARY: "/reports/summary",
  REPORTS_COST_ANALYSIS: "/reports/cost-analysis",
  USERS: "/users",
  DEPARTMENTS: "/departments",
  PERMISSIONS: "/permissions",
  PROFILE: "/profile",
  LOGIN: "/login",
  REGISTER: "/register",
  RESET_PASSWORD: "/reset-password",
  CATEGORY: "/payments/category",
  APPROVALS: "/approvals",
};
